### ISSUE TITLE
5 hours

### ISSUE THREAD

**Issue by oMaikeru** [letsmokee/ApexXPFarmer#9]
After 5 hours of running the tool i always get a prompt where it asks to restart or stop the script, is there anyway to make it as an option configurable via the config?
Its kinda annoying since im using the script while i have no access to my pc and i would like to run it for more than 5 hours

**Comment by letsmokee** [comment]
I don't what's the problem here because my bot currently running for 2 days+. Can you open the bot in CMD and post the logs. Also, there is a feature when you stop Apex (Alt+F4 or whatever), you need to select restarting the bot or just showing the Farm session stats. Maybe your apex crashes after 5 hours and this prompt comes up. I will add to automatically restart after 30 seconda if there is no input from user for the session stats. But post the photo with the logs

**Comment by oMaikeru** [comment]
looks like the problem happens when apex servers crash (they are horrible and happens often) or as you said the game probably crashes itself.
Today when i came back on my pc the script was still running and showing the usual time/exp earned but the game was on the screen where it says that ea servers are unreachable so i basically dont have any error to show will see if anything happens tonight.
If you could add the 30 seconds restart after the prompt to the .exe and maybe post it as prerelease i would appreciate it a lot.

**Comment by letsmokee** [comment]
I have implemented it but currently testing. Today probably release new version because Apex had an update and fill teammates button moved a little bit down. I will close this and test the new version how it manifests when released.
